name: Build Supermodel for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install MSYS2, GCC, Make, and SDL dependencies
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: |
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-SDL2_net

      - name: List all .exe files before build
        shell: msys2 {0}
        run: |
          echo "Listing .exe files before build:"
          find . -type f -iname "*.exe"

      - name: Show installed toolchain for debug
        shell: msys2 {0}
        run: |
          echo "GCC version:"
          gcc --version
          echo "Make version:"
          mingw32-make --version

      - name: Build Supermodel (without network)
        shell: msys2 {0}
        run: |
          set -e
          echo "Starting Supermodel build..."
          mingw32-make -f Makefiles/Makefile.Win32 > build.log 2>&1 || (
            echo "::error::Build failed. Dumping build.log..." &&
            cat build.log &&
            exit 1
          )

      - name: List all .exe files after build
        shell: msys2 {0}
        run: |
          echo "Listing .exe files after build:"
          find . -type f -iname "*.exe"

      - name: Search for Supermodel.exe after build
        shell: msys2 {0}
        run: |
          echo "Searching for Supermodel.exe..."
          find . -type f -iname "Supermodel.exe" || echo "No .exe found"

      - name: Hash Supermodel.exe
        shell: msys2 {0}
        run: |
          echo "SHA256 hash of Supermodel.exe:"
          sha256sum $(find . -type f -iname "Supermodel.exe") || echo "Supermodel.exe not found"

      - name: Upload all .exe files
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Supermodel-Binaries
          path: '**/*.exe'

      - name: Upload build log
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log
